Repository Jahia/javascript-components, pull requests merged in 2019-12, with the labels that each got.

#60 BACKLOG-11783 : Use "auto" for releases
  .gitignore
  package.json
  packages/apollo-dx/.autorc
  packages/design-system-kit/.autorc
  packages/eslint-config/.autorc
  packages/i18next/.autorc
  packages/icons/.autorc
  packages/react-apollo/.autorc
  packages/react-material/.autorc
  packages/react-router/.autorc
  packages/redux/.autorc
  packages/scripts/.autorc
  packages/scripts/auto-include-plugin.js
  packages/scripts/package.json
  packages/scripts/publish.js
  packages/test-framework/.autorc
  packages/ui-extender/.autorc
  yarn.lock
Labels: internal

#61 BACKLOG-11991 : Add stylelint config
  README.md
  packages/stylelint-config/.autorc
  packages/stylelint-config/README.md
  packages/stylelint-config/index.js
  packages/stylelint-config/package.json
  packages/stylelint-config/rules/basicsRules.js
  packages/stylelint-config/rules/orderProperties.js
  packages/stylelint-config/rules/orderTypes.js
  packages/stylelint-config/rules/scssRules.js
  yarn.lock
Labels: major

#62 BACKLOG-11783 : Added documentation
  .env.example
  README.md
Labels: documentation, skip-release

#63 BACKLOG-11783 : Test release
  packages/design-system-kit/README.md
Labels: patch

#64 BACKLOG-11783 : Enable canary builds
  packages/scripts/auto-include-plugin.js
Labels: patch
