Repository Jahia/javascript-components, pull requests merged in 2020-02, with the labels that each got.

#72 BACKLOG-11936: fix ordering of items using numbers instead of strings…
  packages/ui-extender/src/registry/registry.js
Labels: bug, patch

#78 BACKLOG-12359: Upgrade react-apollo in react-material project
  packages/react-material/src/actions/genericDialogMutationAction.jsx
  packages/react-material/src/actions/index.js
  packages/react-material/src/components/NodeTrees/NodeTrees.jsx
  packages/react-material/src/components/PreviewComponent/ImageViewer/ImageViewer.jsx
  packages/react-material/src/components/PreviewComponent/PDFViewer/PDFViewer.jsx
  packages/react-material/src/components/PreviewComponent/PreviewComponent.jsx
  packages/react-material/src/index.js
  packages/react-material/src/picker/PickerTreeViewMaterial.jsx
Labels: dependencies, major

#84 BACKLOG-12339 add mock resolution to jest config for css and scss file
  packages/test-framework/src/jest.config.js
Labels: patch

#89 BACKLOG-11675 : Menu improvements
  packages/react-material/src/actions/buttonRenderer.jsx
  packages/react-material/src/actions/iconButtonRenderer.jsx
  packages/ui-extender/src/actions/core/DisplayAction.d.ts
  packages/ui-extender/src/actions/core/DisplayAction.jsx
  packages/ui-extender/src/actions/core/DisplayActions.d.ts
  packages/ui-extender/src/actions/core/DisplayActions.jsx
  packages/ui-extender/src/actions/menuAction/ContextualMenu.jsx
  packages/ui-extender/src/actions/menuAction/menuAction.jsx
  packages/ui-extender/src/actions/menuAction/menuAction.spec.jsx
  packages/ui-extender/src/actions/menuAction/menuAction.stories.jsx
  packages/ui-extender/src/actions/samples/ButtonRenderer.jsx
Labels: enhancement, minor

#94 BACKLOG-12559: FE Guild - Update stylelint-config dependencies
  packages/stylelint-config/package.json
  yarn.lock
Labels: dependencies
